apiVersion: v1
kind: Service
metadata:
  name: tannaz-service-redis
  namespace: tannaz
  labels:
    app: tannaz-redis
spec:
  type: ClusterIP
  selector:
    app: tannaz-redis
  ports:
    - port: 6379
      targetPort: 6379
