apiVersion: v1
kind: Service
metadata:
  name: tannaz-service-vote
  namespace: tannaz
  labels:
    app: tannaz-vote
spec:
  type: ClusterIP
  selector:
    app: tannaz-vote
  ports:
    - port: 80        # port inside the cluster
      targetPort: 80  # port on the vote container
