apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tannaz
spec:
  type: ClusterIP
  selector:
    app: tannaz-postgres     # same label as your postgres deployment
  ports:
    - port: 5432
      targetPort: 5432
